stages:
- name: build-app
  steps:
  - runScriptConfig:
      image: maven:3.3-jdk-8
      shellScript: mvn clean install
- name: build-container
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: madfromplay/webcatalog:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
- name: Deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
