apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webcatalog
  namespace: default
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-webcatalog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-webcatalog
    spec:
      containers:
      - image: madfromplay/webcatalog:887553c
        imagePullPolicy: Always
        name: webcatalog
        ports:
        - containerPort: 8080
          name: 8080tcp80802
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /app/conf
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          name: webcatalogconfig
          optional: false
        name: vol1
